### ISSUE TITLE
Week 4 Teacher Review

### ISSUE THREAD

**Issue by JakubPonulak** [JakubPonulak/flask_portfolio#21]

**Comment by jm1021** [comment]
Good breakdown of tickets.  Talking about conversion of temperature.   Overall plans 1.0

**Comment by rebecca-123** [comment]
1. Planning: 0.75/1
Comments: README could use table of contents at top to link to the time-boxed sections, and table could be used for each section
2. Team Technicals: 2/2
Comments: Good job dividing up hacks, all individuals seem to have technicals assigned, not sure about Vunsh though. Also, tangible link in the [issue](https://github.com/JakubPonulak/flask_portfolio/issues/12) doesn't work.
3. Individual Technicals:
Anika: 2/2
Comments: Saw work on hacks, nice work on weather page
Jakub: 2/2
Comments: Saw some additions in main.py for hacks, nice implementation of form
Tristan: 2/2
Comments: Nice binary to ASCII conversion
Vunsh: 1.5/2
Comments: Found commits but very few and only for one day during week 4, addition of logo to navbar was nice

Other Comments: 
- missing self-grades
- Github profile commits, plus other links can be combined into a table
- commit comments could maybe be more descriptive
- some issues don't have links to tangibles
- may be better to use README for table for overview of issues and roles, that way you can see the issues and roles for all weeks and develop history of project (looking at issues may be harder to see history)
